version: "3.7"

services:
  billdjpostg:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/billdjpostg
    command:
      # python manage.py migrate 
      # sh -c "python manage.py wait_for_db &&
      #       python manage.py migrate &&
      #       python manage.py runserver 0.0.0.0:8000"
    # command: 
      sleep infinity
    # entrypoint: ["sh", "-c", "sleep 2073600"]
      # python manage.py wait_for_db &&
      # python manage.py migrate &&
      # python manage.py runserver 0.0.0.0:8000

    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres1
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    
    restart: unless-stopped
    # ports:
    #   - 5430:5430
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=supersecretpassword
volumes:
  postgres-data:
