version: "3.7"

services:
  billdjpostg:
    container_name: django_bill
    build: 
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - 8080:8080
    networks: 
      testing_net:
        ipv4_address: 172.28.1.1
      # ports:
      #   - 8100:8100
    volumes:
      - ./app:/billdjpostg
    command:
      # python manage.py migrate 
      # sh -c "python manage.py wait_for_db &&
      #       python manage.py migrate &&
      #       python manage.py runserver 0.0.0.0:8000"
    # command: 
      sleep infinity
    # entrypoint: ["sh", "-c", "sleep 2073600"]
      # python manage.py wait_for_db &&
      # python manage.py migrate &&
      # python manage.py runserver 0.0.0.0:8000

    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres1
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    container_name: postgres_db_bill
    image: postgres:12-alpine
    
    restart: unless-stopped
    
    # ports:
    #   - 5432:5432

    networks: 
      testing_net:
        ipv4_address: 172.28.1.2
      # ports:
      #   - 5432:5432
    
      
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=supersecretpassword
volumes:
  postgres-data:

networks: 
  testing_net:
    ipam: 
      driver: default
      config: 
        - subnet: 172.28.1.0/16