# Generated by Django 2.1.15 on 2020-04-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='CustomerLQ',
        ),
    ]
