# Generated by Django 2.1.15 on 2020-04-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200416_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerLQ',
            new_name='Customer',
        ),
    ]
