# Generated by Django 2.1.15 on 2020-04-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200420_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('NameProduct', models.CharField(max_length=200)),
                ('PriceProduct', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
