version: "3"

services:
  billdjpostg:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../app:/billdjpostg
    # command:

      # sh -c "python manage.py wait_for_db &&
      #       python manage.py migrate &&
      #       python manage.py runserver 0.0.0.0:8000"
    # command: 
      # sleep infinity
    entrypoint: ["sh", "-c", "sleep 2073600"]
      # python manage.py wait_for_db &&
      # python manage.py migrate &&
      # python manage.py runserver 0.0.0.0:8000
    # command: 
      # WORKDIR /app
      # sh -c "python manage.py runserver 127.0.0.1:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres1
      - DB_PASS=supersecretpassword
    depends_on:
      - db

    # links:
    #   - db

  db:
    image: postgres:12-alpine
    
    restart: unless-stopped
    # ports:
    #   - 5430:5430
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=supersecretpassword