# Generated by Django 2.1.15 on 2020-04-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='CustomerID',
            new_name='CustomersID',
        ),
    ]
