# Generated by Django 2.1.15 on 2020-04-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200416_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('SubscriptionID', models.IntegerField(primary_key=True, serialize=False)),
                ('SubscriptionCard', models.CharField(max_length=200)),
                ('CreateDate', models.DateField()),
                ('ExpDate', models.DateField()),
            ],
        ),
    ]
