# Generated by Django 2.1.15 on 2020-04-21 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200421_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipTaxProduct',
            fields=[
                ('RelationshipTaxProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductsID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='productsID', to='core.Product')),
                ('TaxesTypeID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxestypeID', to='core.TaxType')),
            ],
        ),
    ]
