# Generated by Django 2.1.15 on 2020-04-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='SubscriptionID',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
