# Generated by Django 2.1.15 on 2020-04-21 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_relationshiptaxproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='CreateDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
