# Generated by Django 2.1.15 on 2020-04-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200421_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('BillDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('Static_ProductID', models.IntegerField()),
                ('Static_NameProduct', models.CharField(max_length=200)),
                ('Static_PriceProduct', models.DecimalField(decimal_places=2, max_digits=8)),
                ('BillID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billID', to='core.HeadBill')),
            ],
        ),
        migrations.CreateModel(
            name='TaxStatic',
            fields=[
                ('TaxStaticID', models.AutoField(primary_key=True, serialize=False)),
                ('TaxTypeStatic', models.CharField(max_length=200)),
                ('TaxPercentageStatic', models.DecimalField(decimal_places=2, max_digits=4)),
                ('BillDetailID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billdetailID', to='core.BillDetail')),
            ],
        ),
    ]
