# Generated by Django 2.1.15 on 2020-04-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadBill',
            fields=[
                ('HeadBillID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerID', models.IntegerField()),
                ('BillDate', models.DateField()),
                ('BillNumber', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('TaxTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('TaxType', models.CharField(max_length=200)),
                ('TaxPercentage', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
