# Generated by Django 2.1.15 on 2020-04-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_billdetail_taxstatic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headbill',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerID', to='core.Customer'),
        ),
    ]
