# Generated by Django 2.1.15 on 2020-04-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200423_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-LastName']},
        ),
    ]
