# Generated by Django 2.1.15 on 2020-04-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200423_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['SubscriptionID']},
        ),
    ]
