# Generated by Django 2.1.15 on 2020-04-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200423_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['CustomersID']},
        ),
    ]
