# Generated by Django 2.1.15 on 2020-04-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200423_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['NameProduct']},
        ),
    ]
