# Generated by Django 2.1.15 on 2020-04-24 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200423_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headbill',
            name='BillDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
