# Generated by Django 2.1.15 on 2020-04-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200424_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headbill',
            name='BillNumber',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
